require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FilmsController do

  it "should save a film if it is valid" do
    film = Factory.build(:film, :title => 'example')
    film.title.should == 'example'
    Film.stubs(:new).with(film.attributes).returns(film)
    film.expects(:save)
    post :create, :film => film.attributes
  end

end
